add markup for main content in homepage
sandra-selezen/mimino-team-project pull request #9
Opened 2022-12-10 14:07 UTC by vasylenkodi

2022-12-10 17:07 UTC, sandra-selezen requested changes
Якщо по ширині ті картинки, біля яких я залишила коментар, не можна буде знайти одинакових по ширині, то так і залишай поки. 

Головне помісти в контейнер ті секції, що я вказала

2022-12-10 17:07 UTC, sandra-selezen commented on src/partials/about-hotel.html
> +          <img
дві останні картинки теж відрізняються по ширині https://imgur.com/u7jxU7c подивись, чи можна вибрати однакові по ширині? Або потрібно спробувати через стилі за допомогою width примусово задавати ширину

2022-12-10 17:12 UTC, vasylenkodi commented on src/partials/details-restaurant.html
> +  </div>
Исправил

2022-12-10 17:13 UTC, vasylenkodi commented on src/partials/details-hotel.html
> +  <div class="container">
Исправил

2022-12-10 17:18 UTC, vasylenkodi commented on src/partials/about-hotel.html
> +          <img
да, там видимо другие картинки должны быть. Их можно конечно растянуть до нужной ширины но они потом по высоте не будут подходить

2022-12-10 17:18 UTC, vasylenkodi commented on src/partials/details-restaurant.html
> +        <img src="./images/home/mobile/hmpg-12sl-mb.jpg" alt="люди п'ють вино" sizes="(min-width: 1024px) 270px, 274px" />
здесь тоже другая картинка должна быть видимо

2022-12-10 17:19 UTC, vasylenkodi commented on src/partials/about-hotel.html
> +          <img
там еще с одной картинкой такая проблема. В общем надо будет другие последние картинки для слайдеров взять

2022-12-11 11:03 UTC, sandra-selezen requested changes
Перевір, чому при зменшенні екрану, ці картинки зменшуються, а сусідня такою і залишається https://imgur.com/0C3Vkrb https://imgur.com/rQxhIBi

2022-12-11 13:43 UTC, vasylenkodi commented
> Перевір, чому при зменшенні екрану, ці картинки зменшуються, а сусідня такою і залишається https://imgur.com/0C3Vkrb https://imgur.com/rQxhIBi

так должно быть по макету

2022-12-11 14:08 UTC, merged